### ISSUE TITLE
Create a single story "a" character as a stylistic alternative

### ISSUE THREAD

**Issue by stephenkoo** [indestructible-type/Renner#2]
Currently, the italic “a” is single-story while the non-italic “a” is double-story.

I’d like to see Renner* implement a single-story non-italic “a”, and perhaps a double-story italic “a”.

**Comment by EwonRael** [comment]
Hey Stephenkoo!

I'm happy to announce that Renner* version 2.2 now comes with alternative lower case "a"s! Both of the requested styles are now available. 

This is available to download this minute off of GitHub, and will be made available through the website shortly.

Thanks for reaching out with this feature request, and for your patience

**Comment by stephenkoo** [comment]
Hi Ewon,

That's amazing! Can't wait to try it out.

Thanks so much for your hard work! 😃



SK

*Stephen Koo*
+61 4 1329 4230
stephenyrkoo@gmail.com
