### ISSUE TITLE
Alternate version of "ae" is missing

### ISSUE THREAD

**Issue by cdxOo** [indestructible-type/Renner#6]
The font includes the single story 'a' glyph as an alternative, wich I really like. Unfortunately the alternative version for 'ae' (and probably others related to the "a" glyph) are missing,

**Comment by EwonRael** [comment]
I'm looking into this!

You are right about other "a" glyph derivatives missing their single story counterpart. 

However, I am reluctant to make an "ae" ligature alternative, for fear that it will look too much like "oe" as I cannot put the connecting stem on the a, making it virtually indistinguishable from an "o".

**Comment by EwonRael** [comment]
Okay!

As of Renner* 3.0 which was release today, the alternative character set includes "a" glyph derivatives such as à, á, and ä.

I'm not making an alternative "ae" ligature for the reasons specified earlier, but if it is your interest is in having one I suggest using the "oe" ligature to create that effect.

I hope that's helpful.
