### ISSUE TITLE
web font

### ISSUE THREAD

**Issue by petrad** [indestructible-type/Renner#7]
Can I use your font as a webfont hosted on my server if I use the fontsquirrel generator? 
Thank you very much for your font and support!
Petra

**Comment by EwonRael** [comment]
Hey!

You can absolutely use Renner* as a webfont using fontsquirrel! 

I haven't added this to the website yet, but I've started a website that hosts fonts to make webuse easier. Simply add the code below to your website `<head>` and you should be able to use Renner*.

`<link rel="stylesheet" href="https://indestructibletype-fonthosting.github.io/renner.css" type="text/css" charset="utf-8" />`

That way you can skip all the self hosting process, and this system also means that as I update Renner* your website will stay up to date without you having to do anything. 

You are still welcome to self-host if you are so inclined.

Hope that helps!
